name: Build on Push

on:
  push:
    branches:
      - main # Replace with the name of the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Restart Node.js Application with PM2
      run: |
        # Install PM2 globally if not already installed
        npm install -g pm2
        
        # Restart the application with PM2
        pm2 restart 0
