name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Adjust to your Node.js version

    - name: Install Dependencies
      run: npm install  --force

    - name: Build
      run: npm run build
      
    # You can add more steps here, like deploying the built code or publishing artifacts.

